### ISSUE TITLE
Evoweb\StoreFinder\Controller\Event\MapGetLocationsByConstraintsEvent::__construct() must be an instance of TYPO3\CMS\Extbase\Persistence\QueryResultInterface

### ISSUE THREAD

**Issue by webworker-united** [evoWeb/store_finder#35]
hey, in TYPO3 11.5.8 with your current store_finder version 6.0.0, we got this error in frontend:

Argument 2 passed to Evoweb\StoreFinder\Controller\Event\MapGetLocationsByConstraintsEvent::__construct() must be an instance of TYPO3\CMS\Extbase\Persistence\QueryResultInterface, array given, called in /var/www/html/public/typo3conf/ext/store_finder/Classes/Controller/MapController.php on line 191

thanks in advance for solving

**Comment by mschwer** [comment]
Hi @evoWeb , is there any solution in to this problem? I am having the same problem. storefinder_show seems to work correctly, storefinder_map is causing the above written frontend error. 

Thanks for your feedback!

**Comment by marcelmarty** [comment]
Same problem here on TYPO3 11.5.4 and  store_finder 6.0.0

**Comment by studio65digital** [comment]
Same here. TYPO3 Version 11.5.10

**Comment by garbast** [comment]
Should be resolved in branch develop. Please test and i will release the fix as version 6.1.0

**Comment by mschwer** [comment]
Hi @garbast , thanks for the update. Unfortunately it's still not working - even though with an other error:

Argument 1 passed to TYPO3\CMS\Extbase\Persistence\Generic\PersistenceManager::getObjectCountByQuery() must implement interface TYPO3\CMS\Extbase\Persistence\QueryInterface, null given, called in /var/www/html/public/typo3/sysext/extbase/Classes/Persistence/Generic/QueryResult.php on line 117

**Comment by studio65digital** [comment]
Hi @garbast! Same here.

**Comment by garbast** [comment]
In a2aaaa1b I changed how the empty result is provided. Please check if the error is still present in your installation.

**Comment by studio65digital** [comment]
Works wonderful now. Thanks a lot!

**Comment by mschwer** [comment]
Hi @garbast , the last error is now gone, now it's saying 

(1/1) #1618235512 Exception
Country may never be empty query: array ( )

Country is definitly set in the backend. Anything else I have to have in mind concerning "country"?
![example-data](https://user-images.githubusercontent.com/79439971/174235909-c16177a9-a987-4f56-b76b-953967956bb4.png)

**Comment by mschwer** [comment]
Any news or suggestions what could cause the error? @garbast

**Comment by stephangrass** [comment]
Hi, I get also the error Country may never be empty query: array ( ) and don't know why.

Any solution?

**Comment by garbast** [comment]
In which situation does this empty query occure? Did you submit a search before? It indicates that the geocoding query was send to the google api without a country. A search always needs to contain a country. Either from a selectbox in the search form, or via defaultContrains in TypoScript.

**Comment by stephangrass** [comment]
Hi, I will check it again soon.
For now I have problems with the Import.

`storefinder:import 1:/user_upload/locations.xlsx 203 1 {"A": "import_id", "B": "name", "C": "adress", "D": "City", "E": "zipcode", "F": "country", "G": "phone", "H": "email", "I": "url", "J": "icon"} "" ""`

will get the error 

"Too many arguments to "storefinder:import" command, expected arguments ..."

and don't know why ...

**Comment by stephangrass** [comment]
> In which situation does this empty query occure? Did you submit a search before?

If the map is included before the search.

> or via defaultContrains in TypoScript

And how to set the defaultContrains in TypoScript?

**Comment by garbast** [comment]
Please stick to the topic of ...must be an instance of TYPO3\.....

**Comment by garbast** [comment]
I could not reproduce the array problem. If you could please recheck it and give me feedback. Then i would release the current state.

**Comment by garbast** [comment]
Closed due to lack of activity
